CREATE TABLE HOSTELS(
	HOSTEL_ID INTEGER PRIMARY KEY,
	HOSTEL_NAME VARCHAR(10) NOT NULL
);





CREATE TABLE ROOMS(
	ROOM_ID INTEGER PRIMARY KEY,
	ROOM_NO INT NOT NULL,
	HOSTEL_ID INT NOT NULL,
	CAPACITY INT NOT NULL,
	UNIQUE(ROOM_NO,HOSTEL_ID),
	FOREIGN KEY (HOSTEL_ID) REFERENCES HOSTELS(HOSTEL_ID)
);


CREATE TABLE STUDENTS(
	STUDENT_ID INTEGER PRIMARY KEY,
	NAME VARCHAR(30) NOT NULL,
	ROOM_ID INT NOT NULL,
	FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID)
);


CREATE TABLE STUDENT_PHONE(
	PHONE_ID INTEGER PRIMARY KEY,
	STUDENT_ID  INT NOT NULL,
	PHONE_NO VARCHAR(10),
	FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID)
);


CREATE TABLE MAINTENANCE_STAFF(
	STAFF_ID INTEGER PRIMARY KEY,
	STAFF_NAME VARCHAR(30) NOT NULL
);


CREATE TABLE WARDENS(
	WARDEN_ID INTEGER PRIMARY KEY,
	WARDEN_NAME VARCHAR(30) NOT NULL,
	HOSTEL_ID INT NOT NULL,
	FOREIGN KEY (HOSTEL_ID) REFERENCES HOSTELS(HOSTEL_ID)
);



CREATE TABLE COMPLAINTS(
	COMPLAINT_ID INTEGER PRIMARY KEY,
	COMPLAINT_TEXT TEXT NOT NULL,
	STAFF_ID INT NOT NULL,
	STUDENT_ID INT NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (STAFF_ID) REFERENCES MAINTENANCE_STAFF(STAFF_ID),
	FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID)
);


CREATE TABLE COMPLAINT_STATUS(
	STATUS_ID INTEGER PRIMARY KEY,
	COMPLAINT_ID INT NOT NULL ,
	STATUS VARCHAR(20) NOT NULL,
	UPDATED_AT TIMESTAMP,
	FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINTS(COMPLAINT_ID)
);



INSERT INTO HOSTELS VALUES
(1, 'Block A'),
(2, 'Block B');


INSERT INTO ROOMS VALUES
(101, 101, 1, 3),
(102, 102, 1, 2),
(201, 101, 2, 2),
(202, 102, 2, 4);



INSERT INTO STUDENTS VALUES
(1, 'Rahul', 101),
(2, 'Amit', 101),
(3, 'Sneha', 102),
(4, 'Priya', 201),
(5, 'Kiran', 202);


INSERT INTO STUDENT_PHONE VALUES
(1, 1, '9876543210'),
(2, 1, '9123456780'),
(3, 2, '9988776655'),
(4, 3, '9090909090'),
(5, 4, '8888888888');


INSERT INTO MAINTENANCE_STAFF VALUES
(1, 'Ramesh'),
(2, 'Suresh'),
(3, 'Mahesh');



INSERT INTO WARDENS VALUES
(1, 'Mr. Sharma', 1),
(2, 'Ms. Gupta', 2);


INSERT INTO COMPLAINTS VALUES
(1, 'Fan not working', 1, 1, CURRENT_TIMESTAMP),
(2, 'Water leakage', 2, 2, CURRENT_TIMESTAMP),
(3, 'Light not working', 3, 3, CURRENT_TIMESTAMP),
(4, 'Broken window', 1, 4, CURRENT_TIMESTAMP);


INSERT INTO COMPLAINT_STATUS VALUES
(1, 1, 'Pending', CURRENT_TIMESTAMP),
(2, 1, 'In Progress', CURRENT_TIMESTAMP),
(3, 2, 'Resolved', CURRENT_TIMESTAMP),
(4, 3, 'Pending', CURRENT_TIMESTAMP),
(5, 4, 'In Progress', CURRENT_TIMESTAMP);


select * from COMPLAINTS;


SELECT S.NAME,R.ROOM_NO,H.HOSTEL_NAME
FROM STUDENTS S
JOIN ROOMS R ON S.ROOM_ID ==R.ROOM_ID 
JOIN HOSTELS H ON R.HOSTEL_ID==H.HOSTEL_ID 


SELECT S.NAME,C.COMPLAINT_TEXT,MF.STAFF_NAME
FROM STUDENTS S
JOIN COMPLAINTS C ON C.STUDENT_ID ==S.STUDENT_ID 
JOIN MAINTENANCE_STAFF MF ON C.STAFF_ID ==MF.STAFF_ID 

SELECT C.COMPLAINT_ID,C.COMPLAINT_TEXT,C.CREATED_AT,CS.UPDATED_AT,CS.STATUS
FROM COMPLAINTS C
JOIN COMPLAINT_STATUS CS ON C.COMPLAINT_ID==CS.COMPLAINT_ID 







